version: '3'
services:

    pythonapp:
        build: ./src/
        command: sh -c "python3 ingestion.py"
        depends_on:
            mysql:
                condition: service_healthy

    mysql:
        restart: always
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "mysql"]
            timeout: 15s
            retries: 3
        build: ./mysql/
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: db
            MYSQL_ROOT_HOST: '%'